apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  ports:
    - port: 80
  selector:
    app: nextcloud
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nc-pv-claim
  labels:
    app: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nextcloud
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
  labels:
    app: nextcloud
spec:
  selector:
    matchLabels:
      app: nextcloud
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
        tier: frontend
    spec:
      containers:
      - image: nextcloud
        name: nextcloud
        env:
        - name: MYSQL_HOST
          value: nextcloud-mysql
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: nextcloud
        volumeMounts:
        - name: nextcloud-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: nextcloud-persistent-storage
        persistentVolumeClaim:
          claimName: nc-pv-claim
